<?php

namespace FacturaScripts\Core\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 09:38:19.
 */
class DataBaseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DataBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DataBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FacturaScripts\Core\Base\DataBase::getTotalSelects
     * @todo   Implement testGetTotalSelects().
     */
    public function testGetTotalSelects() {
        // Remove the following lines when you implement this test.
        $sql = 'create table prueba (valor1 int, valor2 int);';
        $sql2 = 'insert into prueba(valor1) values(1);';
        $this->object->exec($sql);
        $this->object->exec($sql2);
        
    }

   
    /**
     * @covers FacturaScripts\Core\Base\DataBase::select
     * @todo   Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $sql = 'select valor1 from prueba;';
        $result = $this->object->select($sql);

        $this->assertEquals($result[0]['valor1'],1 );
    }

    /**
     * @covers FacturaScripts\Core\Base\DataBase::exec
     * @todo   Implement testExec().
     */
    public function testExec() {
        // Remove the following lines when you implement this test.
        $sql = 'DELETE FROM prueba WHERE valor= 1;';
        $sql2 =  'SELECT valor1 from prueba;';
        $this->object->exec($sql);
        $this->assertEmpty($this->object->selectLimit($sql2, 1));
    }

    /**
     * @covers FacturaScripts\Core\Base\DataBase::tableExists
     * @todo   Implement testTableExists().
     */
    public function testTableExists() {
        // Remove the following lines when you implement this test.
        
        $this->assertTrue($this->object->tableExists('prueba'));
        
    }



}
